name: rescribe-nlp-dataload
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - astor=0.8.1
  - astroid=2.4.2
  - astunparse=1.6.3
  - autopep8=1.5.3
  - blinker=1.4
  - boto3=1.14.20
  - botocore=1.17.20
  - brotlipy=0.7.0
  - c-ares=1.15.0
  - ca-certificates=2020.6.20
  - cachetools=4.1.1
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - docutils=0.15.2
  - gast=0.3.3
  - google-api-core=1.17.0
  - google-auth=1.17.2
  - google-auth-oauthlib=0.4.1
  - google-cloud-bigquery=1.22.0
  - google-cloud-core=1.3.0
  - google-pasta=0.2.0
  - google-resumable-media=0.5.1
  - googleapis-common-protos=1.51.0
  - grpcio=1.27.2
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=2.10
  - importlib-metadata=1.7.0
  - isort=4.3.21
  - jmespath=0.10.0
  - keras-preprocessing=1.1.0
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libgomp=9.2.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libprotobuf=3.12.3
  - libstdcxx-ng=9.2.0
  - loguru=0.5.0
  - markdown=3.2.2
  - mccabe=0.6.1
  - mypy=0.782
  - mypy_extensions=0.4.3
  - ncurses=6.1
  - numpy=1.18.5
  - oauthlib=3.0.1
  - openssl=1.1.1g
  - opt_einsum=3.2.1
  - pip=20.1.1
  - protobuf=3.12.3
  - psutil=5.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyjwt=1.7.1
  - pylint=2.5.3
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python-dotenv=0.14.0
  - python_abi=3.8
  - pytz=2020.1
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.2.0
  - rsa=4.6
  - s3transfer=0.3.3
  - scipy=1.5.0
  - setuptools=49.1.1
  - six=1.15.0
  - sqlite=3.32.3
  - tensorboard=2.2.2
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.2.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.2.0
  - tensorflow-hub=0.8.0
  - termcolor=1.1.0
  - tk=8.6.10
  - toml=0.10.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - urllib3=1.25.9
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - packaging==20.4
    - pyparsing==2.4.7
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - tokenizers==0.8.1rc1
    - tqdm==4.47.0
    - transformers==3.0.2

