name: rescribe-nlp-training-inter-lib
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.11.0
  - aiohttp=3.6.3
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2020.12.8
  - cachetools=4.2.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.3.1
  - decorator=4.4.2
  - gast=0.3.3
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.2
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=2.10
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - keras-preprocessing=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.1.0
  - markdown=3.3.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - multidict=4.7.6
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - pandas=1.1.5
  - pip=20.3.3
  - protobuf=3.13.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.4
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scipy=1.5.2
  - setuptools=51.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.3.0
  - termcolor=1.1.0
  - tk=8.6.10
  - tqdm=4.54.1
  - typed-ast=1.4.1
  - urllib3=1.26.2
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.4.0
  - zlib=1.2.11
  - pip:
    - loguru==0.5.3
