name: rescribe-nlp-deployment
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.6.2
  - astroid=2.4.2
  - async-timeout=3.0.1
  - attrs=20.2.0
  - autopep8=1.5.4
  - boto3=1.14.60
  - botocore=1.17.60
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.1
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1
  - docutils=0.15.2
  - idna=2.10
  - isort=5.5.2
  - jmespath=0.10.0
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libstdcxx-ng=9.3.0
  - loguru=0.5.0
  - mccabe=0.6.1
  - multidict=4.7.5
  - mypy=0.782
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - numpy=1.19.1
  - openssl=1.1.1g
  - pandas=1.1.2
  - pip=20.2.3
  - psutil=5.7.2
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-dotenv=0.14.0
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - s3transfer=0.3.3
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - urllib3=1.25.10
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.4.2
  - zlib=1.2.11
  - pip:
    - absl-py==0.10.0
    - astunparse==1.6.3
    - cachetools==4.1.1
    - filelock==3.0.12
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.21.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - joblib==0.16.0
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.4
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - regex==2020.7.14
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - tb-nightly==2.4.0a20200914
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.4.0.dev2020091401
    - tf-nightly==2.4.0.dev20200914
    - tokenizers==0.8.1rc2
    - torch==1.6.0
    - tqdm==4.49.0
    - transformers==3.1.0
    - werkzeug==1.0.1
