name: rescribe-nlp-deployment
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - aiohttp=3.6.2
  - astroid=2.4.2
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=20.2.0
  - autopep8=1.5.4
  - blas=1.0
  - blinker=1.4
  - boto3=1.14.60
  - botocore=1.17.60
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.1
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1
  - docutils=0.15.2
  - gast=0.3.3
  - google-pasta=0.2.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=2.10
  - importlib-metadata=2.0.0
  - isort=5.5.2
  - jmespath=0.10.0
  - keras-preprocessing=1.1.2
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.35.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.3.0
  - loguru=0.5.0
  - mccabe=0.6.1
  - multidict=4.7.5
  - mypy=0.782
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - numpy=1.19.1
  - oauthlib=3.1.0
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - pandas=1.1.2
  - pip=20.2.3
  - psutil=5.7.2
  - pyasn1=0.4.8
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyjwt=1.7.1
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-dotenv=0.14.0
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - requests-oauthlib=1.3.0
  - s3transfer=0.3.3
  - scipy=1.6.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.3.0
  - tensorflow=2.2.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.2.0
  - tk=8.6.10
  - toml=0.10.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - urllib3=1.25.10
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.4.2
  - zipp=3.4.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.10.0
    - aiohttp-swagger3==0.5.3
    - cachetools==4.1.1
    - decorator==4.4.2
    - fastjsonschema==2.14.5
    - filelock==3.0.12
    - flatbuffers==1.12
    - future==0.18.2
    - google-auth==1.21.3
    - google-auth-oauthlib==0.4.1
    - grpcio==1.32.0
    - joblib==0.16.0
    - markdown==3.2.2
    - networkx==2.5
    - opt-einsum==3.3.0
    - packaging==20.4
    - protobuf==3.13.0
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - regex==2020.7.14
    - requests==2.24.0
    - rsa==4.6
    - sacremoses==0.0.43
    - scikit-learn==0.24.1
    - sentencepiece==0.1.91
    - strict-rfc3339==0.7
    - tb-nightly==2.4.0a20200914
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - tokenizers==0.8.1rc2
    - torch==1.6.0
    - tqdm==4.49.0
    - transformers==3.1.0
