name: rescribe-nlp-training
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=0.10.0
  - astor=0.8.1
  - astroid=2.3.3
  - astunparse=1.6.3
  - autopep8=1.5.4
  - blas=1.0
  - blinker=1.4
  - boto3=1.14.60
  - botocore=1.17.60
  - brotlipy=0.7.0
  - c-ares=1.16.1
  - ca-certificates=2021.1.19
  - cachetools=4.1.1
  - certifi=2020.12.5
  - cffi=1.14.1
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1.1
  - cudatoolkit=11.0.221
  - docutils=0.15.2
  - gast=0.3.3
  - google-auth=1.21.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=2.10
  - importlib-metadata=1.7.0
  - intel-openmp=2020.2
  - isort=4.3.21
  - jmespath=0.10.0
  - joblib=0.16.0
  - keras-preprocessing=1.1.2
  - krb5=1.18.2
  - lazy-object-proxy=1.5.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libprotobuf=3.13.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libuv=1.40.0
  - loguru=0.5.0
  - markdown=3.2.2
  - mccabe=0.6.1
  - mkl=2020.2
  - mypy=0.782
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.1
  - oauthlib=3.0.1
  - openblas=0.3.10
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - pandas=1.1.2
  - pip=20.2.3
  - protobuf=3.13.0.1
  - psutil=5.7.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyjwt=1.7.1
  - pylint=2.4.4
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-dotenv=0.14.0
  - python_abi=3.8
  - pytorch=1.7.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - s3transfer=0.3.3
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.2.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - urllib3=1.25.10
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - decorator==4.4.2
    - filelock==3.0.12
    - flatbuffers==1.12
    - future==0.18.2
    - networkx==2.5
    - opt-einsum==3.3.0
    - packaging==20.4
    - pyparsing==2.4.7
    - regex==2020.7.14
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - tokenizers==0.8.1rc2
    - tqdm==4.49.0
    - transformers==3.1.0
