name: Upload CLI
on:
  push:
    branches:
      - master
    paths:
      - "cli/**"
      - ".github/workflows/cli.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checks out a copy of the repo
      - uses: actions/checkout@master
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # node npm - cache
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: |
          cd scripts/install
          ./install_cli.sh
          cd -
      - name: build
        run: |
          cd cli
          npm run build:package
          cd -
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: rescribe-cli
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: cli/dist
      - name: invalidate cloudfront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_ID_CLI }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: publish to aur
        env:
          PUBLIC_KEY: ${{ secrets.AUR_CLI_PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.AUR_CLI_PRIVATE_KEY }}
        run:
          cd cli/pub/aur
          ./publish.sh
          cd -
      - name: finish
        run: echo "finished!"
