name: Code Coverage
on:
  pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checks out a copy of the repo
      - uses: actions/checkout@master
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: rescribe-code-coverage # optional
          fail_ci_if_error: false # optional (default = false)
      - name: finish
        run: echo "finished!"
