name: Upload Docs
on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checks out a copy of the repo
      - uses: actions/checkout@master
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: |
          cd docs
          yarn install
          yarn build
          cd -
      - name: copy dist
        run: cp -r docs/dist .github/build-frontend/dist
      - name: upload
        run: |
          cd .github/build-frontend
          yarn install
          yarn run build
          yarn start
          cd -
        env:
          AWS_S3_BUCKET: rescribe-docs
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID_DOCS }}
          AWS_REGION: us-east-1
          SOURCE_DIR: dist
      - name: finish
        run: echo "finished!"
