name: Run NLP Dataload
on:
  push:
    branches:
      - master
    paths:
      - "nlp/dataload/**"
      - ".github/workflows/nlp-dataload.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checks out a copy of the repo
      - uses: actions/checkout@master
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.8
      # python pip - cache
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install dependencies
        run: |
          cd nlp/dataload
          conda env create --file ./environment.yml
          cd -
      - name: Run precommit
        id: precommit
        run: |
          cd nlp/dataload
          ./precommit.sh
          cd -
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker
        id: docker-build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          registry: ${{ steps.login-ecr.outputs.registry }}
          image_name: rescribe-nlp-dataload
          build_extra_args: --build-arg=CACHEBUST=$(date +%s)
          # change image tag to ${{ github.sha }} if you want
          image_tag: latest
          context: nlp
          dockerfile: dataload/Dockerfile
      - name: Run dataload job
        id: run-job
        env:
          ROLE: ${{ secrets.AWS_SAGEMAKER_ROLE }}
          IMAGE_NAME: ${{ steps.docker-build.outputs.FULL_IMAGE_NAME }}
        run: |
          cd nlp/sagemaker
          source $(conda info --base)/etc/profile.d/conda.sh
          conda env create --file ./environment.yml
          conda activate rescribe-nlp-sagemaker
          python3 src/main.py
          conda deactivate
          cd -

      # run training (runs on master branch):
      # - name: Wait for dataload to run
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '5m'
      # - name: Trigger nlp training
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     repository: rescribe-dev/rescribe
      #     event-type: train-nlp
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: finish
        run: echo "finished!"
