name: Upload NLP Deployment
on:
  push:
    branches:
      - main
    paths:
      - "nlp/deployment/**"
      - ".github/workflows/nlp-deployment.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checks out a copy of the repo
      - uses: actions/checkout@main
        with:
          lfs: true
      - name: Checkout lfs objects
        run: git lfs checkout
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          miniconda-version: latest
          python-version: 3.8
      # python pip - cache
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install dependencies
        run: |
          cd nlp/deployment
          conda env create --file ./environment.yml
          cd -
      - name: Run precommit
        id: precommit
        run: |
          cd nlp/deployment
          ./precommit.sh
          cd -
      - name: Generate dist
        id: precommit
        run: |
          cd nlp
          ./build.sh nlp/deployment
          cd -
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker
        id: docker-build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          registry: ${{ steps.login-ecr.outputs.registry }}
          image_name: rescribe-nlp
          # change image tag to ${{ github.sha }} if you want
          image_tag: latest
          context: nlp/deployment
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: aws/ecs-fargate/api-task.json
          container-name: nlp
          image: ${{ steps.docker-build.outputs.FULL_IMAGE_NAME }}
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: rescribe-api
          cluster: fargate
          # wait until service is stable
          wait-for-service-stability: false
      - name: finish
        run: echo "finished!"
