name: Run NLP Datasets Libraries Java
on:
  repository_dispatch:
    types:
      - 'nlp-datasets'
  push:
    branches:
      - main
    paths:
      - "nlp/datasets/libraries/java/**"
      - ".github/workflows/nlp-datasets-libraries-java.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checks out a copy of the repo
      - uses: actions/checkout@main
        with:
          lfs: true
      - name: Checkout lfs objects
        run: git lfs checkout
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        id: install
        run: |
          cd nlp/datasets/libraries/java
          yarn install
          cd -
      - name: Run precommit
        id: precommit
        run: |
          cd nlp/datasets/libraries/java
          yarn run precommit
          cd -
      - name: Build
        id: build
        run: |
          cd nlp/datasets/libraries/java
          yarn run predeploy
          cd -
      - name: Generate dist
        id: dist
        run: |
          cd nlp
          ./build.sh datasets/libraries/java
          cd -
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker
        id: docker-build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          registry: ${{ steps.login-ecr.outputs.registry }}
          image_name: rescribe-nlp-datasets-libraries-java
          build_extra_args: --build-arg=CACHEBUST=$(date)
          # change image tag to ${{ github.sha }} if you want
          image_tag: latest
          context: nlp/datasets/libraries/java
      - name: Create conda environment for deploy
        id: create-conda-env-deploy
        run: |
          cd aws/sagemaker/deploy
          if [ -z "$CONDA_DEFAULT_ENV" ]; then
            source $(conda info --base)/etc/profile.d/conda.sh
          fi
          conda env create --file ./environment.yml
          conda activate rescribe-nlp-sagemaker
          conda deactivate
          cd -
      - name: Run sagemaker datasets libraries
        id: run-sagemaker-datasets-libraries-java
        env:
          ROLE: ${{ secrets.AWS_SAGEMAKER_ROLE }}
          IMAGE_NAME: ${{ steps.docker-build.outputs.FULL_IMAGE_NAME }}
          # compute power for sagemaker
          # see https://aws.amazon.com/sagemaker/pricing/
          # and https://aws.amazon.com/sagemaker/pricing/instance-types/
          INSTANCE_TYPE: ml.m5.large
        run: |
          cd aws/sagemaker/deploy
          if [ -z "$CONDA_DEFAULT_ENV" ]; then
            source $(conda info --base)/etc/profile.d/conda.sh
          fi
          conda activate rescribe-nlp-sagemaker
          python3 src/main.py
          conda deactivate
          cd -
      - name: finish
        run: echo "finished!"
